### ISSUE TITLE
Cannot handle record in UTF-8 format

### ISSUE THREAD

**Issue by czchen** [awslabs/aws-fluent-plugin-kinesis#13] opened 2015-01-16 09:07 UTC
When the record in UTF-8 format, the plugin will raise `Encoding::UndefinedConversionError`. The following is td-agent log.

```
  2015-01-16 07:01:06 +0000 [warn]: emit transaction failed  error_class=Encoding::UndefinedConversionError error=#<Encoding::UndefinedConversionError: "\xE5" from ASCII-8BIT to UTF-8>
    2015-01-16 07:01:06 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.0/lib/fluent/plugin/out_kinesis.rb:100:in `encode'
    2015-01-16 07:01:06 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.0/lib/fluent/plugin/out_kinesis.rb:100:in `to_json'
    2015-01-16 07:01:06 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.0/lib/fluent/plugin/out_kinesis.rb:100:in `format'
```

**Comment by imaifactory** [comment] 2015-01-19 06:50
Hi @czchen thanks for reporting. I will look into this.  Can you tell  your use case a bit more?

**Comment by czchen** [comment] 2015-01-19 11:49
Hi @imaifactory 

The following is part of our current `td-agent.conf`. The filter before `aws-fluent-plugin-kinesis` is `exec_filter`. The script `filter.py` is a python2 script, and it might output unicode character in `\uxxxx` format. The data might contain illegal UTF-8 sequence.

```
<match extracted_query.*.*>
  type exec_filter
  command /etc/td-agent/filter.py
  in_format json
  out_format json
  time_key time
  in_tag_key tag
  out_tag_key tag
</match>

<match extracted.*.*>
  type kinesis
...
</match>

```

I am not familiar with ruby, but the patch [0] can solve the issue. Not sure if this is the correct way to do so.


[0] https://github.com/czchen/aws-fluent-plugin-kinesis/commit/aaf8e20586a83b8371a44aa0456abb384e04a235

**Comment by imaifactory** [comment] 2015-01-20 04:03
Thank you for sharing your use case in detail and workaround. I will talk this with my team.

**Comment by imaifactory** [comment] 2015-01-20 22:33
@czchen 

I have talked with my team about workaround for this, including using Yajl.
We have to make sure not to destroy existing users so I have to do some clarification work. It may take time a bit more. 

Please let me clarify that your python code will emit JSON like this?

```
{"some_key":"\uxxx"}
```

**Comment by czchen** [comment] 2015-01-21 06:29
Yes, our `filter.py` would emit emit something like `{"some_key":"\uxxx"}`.

I think you can add a configuration to set how to handle invalid unicode. The default value can be the same as current one (raise an exception).

**Comment by tomasiew** [comment] 2015-01-21 22:11
Reproducible with:

```sh
echo "[\"mytag\",$(date +%s),{\"foo\":\"bar\\uD800\"}]" | nc localhost 24224
```

(UndefinedConversionError is emitted in the fluentd log)

I suspect not everyone will want to ignore these errors, so making this a configuration as @czchen suggested might be a good idea.

**Comment by imaifactory** [comment] 2015-01-23 01:14
Thanks guys. We will work on this and yes, will do care those who do not want ignore errors.

**Comment by az3** [comment] 2015-02-16 13:42
I also experienced this, only when using `detach_process 0` in the config file (w/ td-agent). If I use `detach_process 1` (or more), records are parsed perfectly. Just to let you know... Thanks.

**Comment by jhappoldt** [comment] 2015-06-02 14:17
Thanks for looking at this problem @imaifactory.  Do you know of a workaround for this problem that will allow us to send UTF-8 encoded data into Kinesis while the fix is developed?

Thanks!

**Comment by tamtam180** [comment] 2015-06-03 10:28
I got this error with below config, too.
I think tail-plugin's buffer use `force_encoding('ASCII-8BIT')`,
So `record` in kinesis-plugin's format function has ASCII-8BIT string.

```
def format(tag, time, record)
  log.info(record.inspect)
    # -> {"logType"=>"ads", "abc"=>"\xE3\x82\xA4\xE3\x83\xB3\xE3\x82\xB9\xE3\x83\x88\xE3\x83\xBC\xE3\x83\xAB", "time"=>"2015-05-17T03:00:00Z", "tag"=>"aaaaa"}
  log.info(record["abc"].encoding)
    # -> ASCII-8BIT
```

My workaround is use to `Yajl.dump(record)` instead of `record.to_json`.
How's that sound?

```test.log
{"logType":"ads","abc":"インストール","timestamp":1431831600}
```

```td-agent.conf
<source>
  type tail
  format json
  path /var/log/tmp/test.log
  pos_file /var/log/test.pos
  tag aaaaa
</source>
<match smart-ad.beacon.ads>
  type copy

  <store>
    type                  kinesis
    stream_name           hogefuga
    region                ap-northeast-1
    random_partition_key  true
    num_threads           10

    #buffer_type           file
    #buffer_path           /var/log/kinesis/xxx/
    #try_flush_interval    1s
    #flush_interval        1s
    #buffer_chunk_limit    64m
    #buffer_queue_limit    1024
    #retry_wait            60s
    #max_retry_wait        300s
    #retry_limit           4320
  </store>
  #<store>
  #  type flowcounter
  #  count_keys *
  #  unit minute
  #  aggregate all
  #  tag xxx
  #</store>
</match>
```

**Comment by imaifactory** [comment] 2015-06-04 05:14
@jhappoldt @tamtam180 
Thanks for bumping this. I agree with @tamtam180 , we should use `Yajl.Dump`. 
Do you guys think we will have any trade off by switching to this?

**Comment by tamtam180** [comment] 2015-06-04 13:26
I'm sorry I have no idea, but it works for me. (now load testing)
(Maybe, Date/Time class in record of encoding might not be compatible.)

**Comment by imaifactory** [comment] 2015-06-11 23:24
@tamtam180 

Thank you for your clarification and waiting.
As we talked in offline, I think we should implement it as an option.
I will work on this.

**Comment by imaifactory** [comment] 2015-07-07 01:21
Thanks to everyone here, we have pushed the fixed version!
https://rubygems.org/gems/fluent-plugin-kinesis/versions/0.3.4

**Closed by imaifactory** 2015-07-07 01:21 UTC
