### ISSUE TITLE
fluentd-kinesis dies when max ram buffer size has been reached

### ISSUE THREAD

**Issue by mperriere** [awslabs/aws-fluent-plugin-kinesis#89] opened 2016-10-21 08:29 UTC
Hello,
we use kinesis plugin to forward a 50Mbytes/s stream to a 80 Shards kinesis.
Unfortunately, when we simulate a kinesis connexion loss, or invalid credentials, or kinesis unreachable, the fluentd processe dies when the ram buffer is full.

Here is the kinesis output configuration:
<match apache.**>
  @type copy
  deep_copy
  <store>
    @id out_kinesis
    @type kinesis_streams
    region eu-west-1
    stream_name STREAMING_FLUENTD
    num_threads 20
    buffer_chunk_limit 4m
    buffer_queue_limit 128
    try_flush_interval 1s
    queued_chunk_flush_interval 0.1
    retry_wait 1s
    retries_on_batch_request 10
  </store>

We check buffer size with:
KINESIS_BUFFER_SIZE=$(curl -s -q http://$HOSTNAME:24220/api/plugins.json | jq '.plugins[3] | .buffer_total_queued_size | select(. >= 0)')

when 512Mb buffer has been reached, fluentd stop sending data to kinesis instead of dropping the oldest data. And max_buffer_size is stalled to that max value.

PS: on the same fluentd configuration, we send in parallel the same data to an S3 repo. When kinesis start to fail, the S3 output drops to 0Mb/s too.
The only fix is to restart the whole fluentd process (kinesis data on ram is lost).

**Comment by riywo** [comment] 2016-10-21 08:39
Hi,

Thank you for reporting the issue. I'd like to make it clearer.

Do you mean fluentd process dies or it is alive but not working when the memory buffer is full? What is your expected behavior if the memory buffer is full and kinesis continues unavailable?

Also, why don't you use file buffer instead? It is more durable than memory buffer.

Best,

**Comment by mperriere** [comment] 2016-10-21 09:54
When working properly, the fluentd process consumes 80% of CPU on our EC2.
When reaching max buffer size, the CPU drops down to 1%.
Process does not die but does nothing.
I did not find anything special in the logs when the issue occurs.


We don't use file buffer  (that's the one we use with fluentd-s3) because we had a few random errors with it.
In a few words, we inject the same 1Go raw apache log in a loop to validate the plugin stability in the long run. And after a few days, the disk buffer gets corrupted. A line becomes unreadable, and plugins gets stucked. This in a bit strange, as the same sample has been procedded correctly a thousand times before generating a issue in the buffer, many days after the hit injection started.

**Comment by comtef** [comment] 2016-10-21 16:11
Hello,
I'm working with mperriere on the subject.
We send data to both S3 and Kinesis and our SLA for Kinesis is lower so we accept to use a memory buffer (S3 plugin use a file buffer).
We expect the kinesis plugin to drop chunks when its buffer is full and it should not affect others plugins. It should not matters why the buffer is full (Kinesis unavailable, data throughput too low), older chunks should be discarded.

**Comment by riywo** [comment] 2016-10-22 03:30
Thank you for describing. Could you also provide the version of this plugin, fluentd, and ruby?

**Comment by riywo** [comment] 2016-10-22 06:30
Also, how did you simulate a kinesis connexion loss, invalid credentials, or kinesis unreachable?

**Comment by mperriere** [comment] 2016-10-24 08:59
Versions:
fluentd-2.3.3 (td-agent-2.3.3-0.el7.x86_64.rpm)
fluent-plugin-kinesis 1.1.1.
Ruby version is packaged with fluentd/td-agent:
ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

I did simulate the kinesis connexion loss by removing the kinesis instance, or removing credentials, with fluentd already started.

**Comment by riywo** [comment] 2016-11-21 16:56
Hi @mperriere and @comtef ,

Sorry for my late reply. I found that fluentd itself has an exact option which you want since v0.12.24:

`buffer_queue_full_action drop_oldest_chunk`

https://github.com/fluent/fluentd/pull/934

td-agent v2.3.3 contains fluentd 0.12.29, so you can use this option.

I'm going to close this issue, but feel free to comment if it doesn't work.

Thanks,

**Closed by riywo** 2016-11-21 16:56 UTC
Labels: need more info
