### ISSUE TITLE
"kinesis_producer" results in 2x CPU consumption as "kinesis_streams"

### ISSUE THREAD

**Issue by tehranian** [awslabs/aws-fluent-plugin-kinesis#66] opened 2016-05-02 23:42 UTC
Hi there,

I work at [Twilio](https://www.twilio.com) (a major AWS customer) and we're using fluentd & Kinesis as part of a log aggregation solution for our microservices.

I was very excited to see the 1.0 release of this plugin which added support for the C-based KPL log-shipper. Unfortunately in our testing, the KPL-based "kinesis_producer" output plugin seems to cause fluentd's "ruby2.0" process to consume >2x the CPU utilization vs using the "kinesis_streams" plugin. Ex: At 1,000 messages/second we see ~10% CPU usage with "kinesis_streams" and ~24% CPU% with "kinesis_producer".

Any thoughts/comments? Is this expected? Any thoughts on why the CPU consumption for the "ruby2.0" process with "kinesis_producer" would be so much higher?

Thanks,
Dan

**Comment by riywo** [comment] 2016-05-04 05:48
Hi @tehranian 

Thank you for reporting this. So far I don't have any idea of this cpu consumption. I'd like to reproduce it, could you share your fluent.conf without any credentials or sensitive data?

**Comment by tehranian** [comment] 2016-05-04 18:28
Hi @riywo ,

Thanks for the response. I simplified our config down to this and reproduced with the results below:

```
2016-05-04 11:10:14 -0700 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
  <source>
    type tail
    format /^(?<message>.*)$/
    tag app.chunder-webrtc-gateway.logspammer
    path /var/log/twilio/logspammer.log
    read_from_head true
    read_lines_limit 1000
    pos_file /mnt/services/twilio-fluentd/twilio-fluentd.log.pos
  </source>
  <source>
    type monitor_agent
    bind 127.0.0.1
    port 19837
  </source>
  <match app.** service.** system.**>
    @type kinesis_producer
    id kinesis-out
    time_format %FT%T%:z
    stream_name log-stream-dev
    region us-east-1
    include_time_key true
    include_tag_key true
    num_threads 1
    max_retry_wait 300
    disable_retry_limit true
    flush_interval 10s
    <kinesis_producer>
    </kinesis_producer>
  </match>
  <system>
    log_level info
  </system>
</ROOT>
```

* Pushing 1,000 messages / second to the above `/var/log/twilio/logspammer.log`, I see CPU utilization of the `ruby2.0` process at 22% of 1 core as reported by Datadog. FWIW - Looking in `top`, I see a great deal of variance in that CPU utilization over time... Ex: The ruby process is frequently at 2-5% CPU, with sustained bursts at 60-70% CPU.

* Using the same config/load, but substituting `kinesis_streams` for `kinesis_producer`, I see CPU utilization at 8-9% as reported by Datadog, and 3-25% in `top`.

My hunch is that this has to do with marshaling between the Ruby process and the KPL agent via Protobufs over named pipes. What're your thoughts?

**Comment by cbroglie** [comment] 2016-05-17 04:13
We're encountering a similar issue in that our throughput is bound by CPU time. I captured a profile (https://gist.github.com/cbroglie/907f631e313c23d346c31e40094b1452), and it does appear to be serialization related.

**Comment by riywo** [comment] 2016-05-17 06:52
Hi @tehranian and @cbroglie 

Thank you for the information. Yes, this plugin uses pure-ruby protobug library so that it will cost somehow to serialize/deserialize. There is another protobuf library using native code, but it is still alpha version. If it will be released GA version, I will use that.

**Comment by riywo** [comment] 2016-05-18 00:34
I've also took ruby-prof both streams and producer, and I can see the protobuf methods take much CPU time.
https://github.com/awslabs/aws-fluent-plugin-kinesis/tree/work/profile/profile

I'm going to test [google-protobuf](https://rubygems.org/gems/google-protobuf) which uses native code (though still alpha). If it works fine, I'll consider whether I can add an experimental option to use this library for serialize/deserialize.

**Comment by cbroglie** [comment] 2016-05-18 01:38
I tried testing that earlier today but the problem is it only supports proto3, and the KPL is using proto2. I opened up an issue for the KPL project regarding that: https://github.com/awslabs/amazon-kinesis-producer/issues/52.

**Comment by wryun** [comment] 2016-06-06 00:01
We are successfully using the alpha version of the google plugin which has moderate CPU usage in https://github.com/atlassian/fluent-plugin-kinesis-aggregation

(was developed before this plugin supported aggregated records)

There's a nasty hack to get around the proto2 vs proto3 issue :)

**Comment by cbroglie** [comment] 2016-06-06 21:15
@wryun Interesting, thanks for sharing. Looks like https://github.com/atlassian/fluent-plugin-kinesis-aggregation/commit/4b80e987c4c91c3374a34bb44cce852ed9aa6a9a is the commit demonstrating how to use it the Google library with proto2. Have you encountered any issues using the alpha version of google-protobuf?

**Comment by wryun** [comment] 2016-06-08 08:00
No, it's been working smoothly across the organisation (many many terabytes :) ). But that plugin is very much tuned for our use-case.

**Comment by cbroglie** [comment] 2016-06-29 03:35
We moved over to https://github.com/atlassian/fluent-plugin-kinesis-aggregation as well. Using the google-protobuf library makes it much more performant, and since fluentd is already doing the buffering to aggregate records, I don't see any reason to deal with the additional complexity of the KPL.

**Comment by riywo** [comment] 2017-02-01 10:13
#101 will resolve this. So, I'd like to close this issue.

**Closed by riywo** 2017-02-01 10:13 UTC
Labels: enhancement
